apiVersion: apps/v1
kind: Deployment
metadata:
  name: authors-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authors-pod
  template:
    metadata:
      labels:
        app: authors-pod
    spec:
      containers:
      - name: authors
        image: leonbd/api-project
        ports:
        - containerPort: 80
